## Configuration file for MeBaPiNa

## Analysis configuration

experiments:
  ## path to directory containing main folders (00_raw_data, 01_processed_data, ...)
  project: "/mnt/ag-halama/PROMISE/.tmp" # "/mnt/Nanopore/Nanopore_Projects/Internal/NCT/PROMISE/Microbiome/16S_Metabarcoding/"
  tmp: "16S_Metabarcoding/"
  ## samples to analyze, matching "Sample name"s in EXPERIMENT_SEQUENCING.xlsx #!# currently only one single run analysis is supported
  samples: 
    ["NTC", 
    "Extraction-control", 
    "ZymoDNA", 
    "ZymoCell", 
    "OP61", 
    "PROM-01-0001-MS-T1T2", 
    "PROM-01-0002-MS-T1T2", 
    "PROM-01-0001-MS-T2ERW", 
    "PROM-01-0003-MS-T1T2", 
    "PROM-01-0004-MS-T1T2", 
    "PROM-01-0005-MS-T1T2", 
    "PROM-01-0002-MS-T2ERW"]

methodologie:
    "kmer" ## one of "kmer", "align", "otu", "asv"

workstation:
  gpu: True
  cpu: 12

filtering:
  q_min: "7" ## deactivate quality filtering by setting it to "0"
  len_min: "1000"
  len_max: "2800"
  min_featurereads: "3" ## minimum number of reads per cluster or taxon
  min_readidentity: "0.85" ## minimum read identity for clustering
  min_confidence: "0.0"

reference:
  source: "silva"
  type: "species" ## one of "default", "species", "genus"; species and genus only in conjuction with source: "silva"
