## Configuration file for MeBaPiNa

## Analysis configuration

experiments:
  ## path to directory containing main folders (00_raw_data, 01_processed_data, ...)
  project: "/mnt/Nanopore/Nanopore_Projects/Internal/NCT/PROMISE/Microbiome/16S_Metabarcoding"
  ## samples to analyze, matching "Sample name"s in EXPERIMENT_SEQUENCING.xlsx #!# currently only one single run analysis is supported
  samples: 
    ["NTC", 
    "Extraction-control", 
    "ZymoDNA", 
    "ZymoCell", 
    "OP61", 
    "PROM-01-0001-MS-T1T2", 
    "PROM-01-0002-MS-T1T2", 
    "PROM-01-0001-MS-T2ERW", 
    "PROM-01-0003-MS-T1T2", 
    "PROM-01-0004-MS-T1T2", 
    "PROM-01-0005-MS-T1T2", 
    "PROM-01-0002-MS-T2ERW"]

workstation:
  gpu: True
  cpu: 12

filtering:
  q_min: "7" ## deactivate quality filtering by setting it to "0"
  len_min: "1000"
  len_max: "2800"

align:
  reference: "silva" # "kraken2/silva_132_species"
