## Configuration file for MeBaPiNa

## Analysis configuration

experiment_directory:
  ## path to directory containing main folders (00_rawdata, 01_processeddata, ...)
  base: "/ag-halama/Microbiome/16S_Metabarcoding"
  ## run folder structure generated bay MinKNOW
  run: "16S_nanopore_primer/Testpool/20191007_1559_MN31344_FAK76605_2bf006ff"

machine:
  gpu: False
  cpu: 12

guppy:
  ## run set-up
  flowcell: "FLO-MIN106"
  seq_kit: "SQK-RAB204"
  bac_kit: "SQK-RAB204" ## deactivate analysis of barcoodes by leaving it empty: "" Note: this doesn't deactivate demultiplexing, only the analysis of the individual barcodes
  lam_DCS: False ## deactivate detection of Lambda calibration strands by setting it: False
  ## basecalling
  q_min: "0" ## deactivate quality filtering by setting it to "0"
  len_min: "1000"
  len_max: "2800"

align:
  reference: "silva_arb/SILVA_132_SSURef_Nr99_tax_silva" ## don't add fasta ending

## TODO: use shema and add from snakemake.utils import validate to Snakefile
