## Configuration file for MeBaPiNa

## Analysis configuration

experiments:
  ## path to directory containing main folders (00_raw_data, 01_processed_data, ...)
  project: "/mnt/ag-halama/PROMISE/.tmp" #!# "/mnt/Nanopore/Nanopore_Projects/Internal/NCT/PROMISE/Microbiome/16S_Metabarcoding/"
  tmp: "16S_Metabarcoding/" #!# was required because snakemake does not work when located on the NAS (links are broken). Hence the paths above could not be used, but the execution has to be performed from the base directory (e.g. 16s_Metabarcoding)
  ## path to the excel file containing the metadata
  meta: "METADATA/EXPERIMENT_SEQUENCING.xlsx"
  ## path to the csv file logs are written to
  log: "METADATA/ANALYSIS_PROGRESS_MANAGEMENT.csv"
  ## samples to analyze, matching "Sample name"s in EXPERIMENT_SEQUENCING.xlsx #!# currently only one single run analysis is supported
  samples:
    ["NTC",
    "Extraction-control",
    "ZymoDNA",
    "ZymoCell",
    "OP61",
    "PROM-01-0001-MS-T1T2",
    "PROM-01-0002-MS-T1T2",
    "PROM-01-0001-MS-T2ERW",
    "PROM-01-0003-MS-T1T2",
    "PROM-01-0004-MS-T1T2",
    "PROM-01-0005-MS-T1T2",
    "PROM-01-0002-MS-T2ERW"]
    # ["NTC",
    # "Extraction-control",
    # "ZymoDNA","Lu5",
    # "Lu13",
    # "Lu18",
    # "Extraction-control-enriched",
    # "Lu5-enriched",
    # "Lu13-enriched",
    # "Lu18-enriched",
    # "Lu5",
    # "Ov85"]

methodologie:
  ["kmer", "align"] ## one (or multiple of ) ["kmer", "align", "otu"]. The "asv" mehtodolgie is not supported.

workstation:
  gpu: True
  cpu: 12

filtering:
  q_min: "7" ## deactivate quality filtering by setting it to "0"
  len_min: "1000"
  len_max: "2800"
  min_featurereads: "3" ## minimum number of reads per cluster or taxon
  min_readidentity: "0.85" ## minimum read identity for clustering
  min_confidence: "0.0" ## confidence used for calssification of taxa at species level
  plot_sample: "100000" ## downsampling reads in plots to this number to reduce computational complexity (distorts statistics shown in some plots)

reference:
  source: "silva"
  rank: "Species" ## one of "default", "Species", "Genus"; species and genus only in conjuction with source: "silva"
